config/routes.rb
Rails.application.routes.draw do

  root 'landing/v1#index'

  namespace :landing do
    get '/' => 'v1#index'
  end

  namespace :investee do
    get '/' => 'dashboard#index'
    resources :projects
  end

  namespace :investor do
    get '/' => 'dashboard#index'
  end

  namespace :v1, defaults:  { format: :json } do
    resource  :login, only: [:create], controller: :sessions
    resources :users, only: [:create]
    resources :projects do 
      collection do 
        get 'investee'
        get 'investor'
      end
    end
    get 'test' => 'main#test'
  end

  devise_for :users, 
  :controllers => {:registrations => "registrations"}, 
  :path => '', 
  :path_names => {:sign_in => 'id', :sign_out => 'logout', :sign_up => 'registration'}   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/investee.rb
class Investee < ApplicationRecord
  belongs_to :user
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :investee

  before_create :set_user

  def set_user
  end

end

app/controllers/investee/dashboard_controller.rb
class Investee::DashboardController < ApplicationController

  before_action :set_user_type

  def index
  end

  private
  def set_user_type
  	if current_user.usertype === 2
  		redirect_to :investor
  	end
  end
end

app/controllers/investee/projects_controller.rb
class Investee::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  layout 'investee/dashboard'

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.where(investee_id: current_user.investee.id)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to investee_projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:investee_id, :tile, :description, :image, :videolink, :site, :mission)
    end
end

app/controllers/v1/projects_controller.rb
class V1::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  
  skip_before_action :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' } 


  # GET /v1/projects/investee
  # params access_token

  def investee
    auth_token = request.headers['Authorization']
    if auth_token
      @user = User.where(access_token: auth_token).last
      @projects = @user.investee.projects
      render json: @projects, each_serializer: V1::ProjectsSerializer, root: false
    else
     render json: 500
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    render json: @projects, each_serializer: V1::ProjectsSerializer, root: false
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /v1/projects
  def create
    @project = Project.new(project_params)
    auth_token = request.headers['Authorization']
    @user = User.all.where(access_token: auth_token).last
    @project.investee_id = @user.investee.id
    if @project.save
      render json: @project
    else
      render json: 500
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:investee_id, :tile, :description, :image, :videolink, :site, :mission)
    end
end

app/helpers/investee/dashboard_helper.rb
module Investee::DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/investee/projects/_form.haml
= simple_form_for [:investee, @project], class: "form-horizontal" do |f|
  = f.error_notification
  .form-inputs
    = f.input :investee_id, label: false, input_html: {value: "#{current_user.investee.id}", type: "hidden"}
    = f.input :tile, label: "Название", input_html: {class: "form-control"}
    = f.input :description, input_html: {class: "form-control"}
    = f.input :image, input_html: {class: "form-control"}
    = f.input :videolink, input_html: {class: "form-control"}
    = f.input :site, input_html: {class: "form-control"}
    = f.input :mission, input_html: {class: "form-control"}
  .form-actions
    = f.button :submit

app/views/investee/projects/_project.haml
.col-md-3
  = link_to project.tile, investee_project_path(project)

app/views/investee/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/investee/projects/index.haml
= link_to "Добавить проект", new_investee_project_path, class: "btn btn-success"

- unless current_user.investee.projects.present?
  %p В настоящий момент у Вас нет открытых проектов.
- else
  .row
    = render @projects

app/views/investee/projects/new.haml
%h3 Добавить проект
= render 'form', project: @project

app/views/investee/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Investee:</strong>
  <%= @project.investee.user.email %>
</p>

<p>
  <strong>Tile:</strong>
  <%= @project.tile %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @project.image %>
</p>

<p>
  <strong>Videolink:</strong>
  <%= @project.videolink %>
</p>

<p>
  <strong>Site:</strong>
  <%= @project.site %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @project.mission %>
</p>